### ISSUE TITLE
ERROR: Cannot promisify an API that has normal methods in dynasty

### ISSUE THREAD

**Issue by jsalwen** [joshuahoover/botkit-storage-dynamodb#7]
Dynasty appears to be causing an error in v 0.2.0

Here is the error I get when starting my `botkit` server

```cmd
>node server.js
c:\botdir\node_modules\dynasty\node_modules\bluebird\js\main\promisify.js:55
                    throw new TypeError("Cannot promisify an API that has normal methods with '%s'-suffix\u000a\u000a    See http://goo.gl/iWrZbw\u000a"
                    ^

TypeError: Cannot promisify an API that has normal methods with 'Async'-suffix

    See http://goo.gl/iWrZbw

    at checkValid (c:\botdir\node_modules\dynasty\node_modules\bluebird\js\main\promisify.js:55:27)
    at promisifiableMethods (c:\botdir\node_modules\dynasty\node_modules\bluebird\js\main\promisify.js:78:5)
    at promisifyAll (c:\botdir\node_modules\dynasty\node_modules\bluebird\js\main\promisify.js:241:9)
    at Function.Promise.promisifyAll (c:\botdir\node_modules\dynasty\node_modules\bluebird\js\main\promisify.js:304:12)
    at new Dynasty (c:\botdir\node_modules\dynasty\lib\dynasty.js:39:15)
    at module.exports (c:\botdir\node_modules\dynasty\lib\dynasty.js:224:12)
    at module.exports (c:\botdir\node_modules\botkit-storage-dynamodb\src\index.js:17:32)
    at Object.<anonymous> (c:\botdir\app\controllers\botkit_facebook.js:15:53)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Server.server.listen (c:\botdir\server.js:35:3)
    at Server.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:185:7)
    at emitListeningNT (net.js:1288:10)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by jsalwen** [comment]
It appears to be related to `aws-sdk` which is used by `dynasty`
https://github.com/aws/aws-sdk-js/issues/2229

**Comment by jsalwen** [comment]
workaround: install `aws-sdk` version `2.304.0`

```console
npm install aws-sdk@2.304.0
```
